import { useState } from "react"

import Head from "next/head"

import { BsFillMoonStarsFill } from "react-icons/bs"
import {
  AiOutlineInstagram,
  AiFillLinkedin,
  AiOutlineGithub,
} from "react-icons/ai"

import Image from "next/image"
import deved from "../public/dev-ed-wave.png"
import design from "../public/design.png"
import code from "../public/code.png"
import consulting from "../public/consulting.png"
import web1 from "../public/web1.png"
import web2 from "../public/web2.png"
import web3 from "../public/web3.png"
import web4 from "../public/web4.png"
import web5 from "../public/web5.png"
import web6 from "../public/web6.png"

export default function Home() {
  const [darkMode, setDarkMode] = useState(false)

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Alerrandro Janio Portifólio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className=" h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-white">
              alerrandro.dev
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-xl hover:text-teal-600 dark:text-white dark:hover:text-teal-600 "
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font font-medium md:text-6xl">
              Alerrandro Janio
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Fullstack Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-400">
              Graduando Sistemas de Informação na UFC, como também trabalhando
              como suporte de TI e auxiliar no setor financeiro do LAC Dr. José
              Maria Leitão.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a
              href="https://www.linkedin.com/in/alerrandrojanio/"
              target="_blank"
              without
              rel="noreferrer"
            >
              <AiFillLinkedin className="hover:text-teal-600 dark:hover:text-teal-600" />
            </a>
            <a
              href="https://www.github.com/alerrandrojanio"
              target="_blank"
              without
              rel="noreferrer"
            >
              <AiOutlineGithub className="hover:text-teal-600 dark:hover:text-teal-600" />
            </a>
            <a
              href="https://www.instagram.com/alerrandrojanio"
              target="_blank"
              without
              rel="noreferrer"
            >
              <AiOutlineInstagram className="hover:text-teal-600 dark:hover:text-teal-600" />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:w-96 md:h-96">
            <Image src={deved} layout="fill" objectFit="cover" alt="Avatar" />
          </div>
        </section>

        <section className="mt-20">
          <div className="text-center">
            <h3 className="text-3xl py-1 dark:text-white">
              Servicos que ofereço
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 md:text-xl max-w-3xl mx-auto dark:text-gray-400">
              <span className="text-teal-500">Técnico em Informática</span> com
              conhecimentos tanto
              <span className="text-teal-500"> front-end</span> (HTML, CSS, JS),
              <span className="text-teal-500"> frameworks</span> (VueJs e React)
              quanto em <span className="text-teal-500">back-end </span>
              (Node.js, C# e Java), além de banco de dados{" "}
              <span className="text-teal-500">SQL</span> (MySQL, PostgreSQL e
              SQL Server).
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 md:text-xl max-w-3xl mx-auto dark:text-gray-400">
              Com experiência básica em outras linguagens como Php e Python.
              Atualmente estudando a fundo a plataforma .NET e também
              desenvolvimento web com React.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image
                src={design}
                className="mx-auto"
                width={100}
                alt="Logo design"
              />
              <h3 className="text-lg font-medium pt-8 pb-2">Lindos Designs</h3>
              <p className="py-2">Design elegante para suas imagens.</p>
              <h4 className="py-4 text-teal-600">Ferramentas de design</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Ilustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image
                src={code}
                className="mx-auto"
                width={100}
                alt="Logo desenvolvimento"
              />
              <h3 className="text-lg font-medium pt-8 pb-2">Lindos Designs</h3>
              <p className="py-2">Design elegante para suas imagens.</p>
              <h4 className="py-4 text-teal-600">Ferramentas de design</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Ilustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image
                src={consulting}
                className="mx-auto"
                width={100}
                alt="Logo consultoria"
              />
              <h3 className="text-lg font-medium pt-8 pb-2">Lindos Designs</h3>
              <p className="py-2">Design elegante para suas imagens.</p>
              <h4 className="py-4 text-teal-600">Ferramentas de design</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Ilustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
          </div>
        </section>

        <section>
          <div className="text-center">
            <h3 className="text-3xl py-1 dark:text-white">Portifolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 md:text-xl max-w-3xl mx-auto dark:text-gray-400">
              Buscanco apender cada vez mais sobre{" "}
              <span className="text-teal-500">APIs em C# </span>e Front-end com{" "}
              <span className="text-teal-500">React.</span>
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                src={web1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt="Projeto de portifólio 1"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web2}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt="Projeto de portifólio 2"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web3}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt="Projeto de portifólio 3"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web4}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt="Projeto de portifólio 4"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web5}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt="Projeto de portifólio 5"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web6}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt="Projeto de portifólio 6"
              />
            </div>
          </div>
        </section>
        <div className="w-full flex justify-between items-center md:flex-row flex-col pt-6 border-t-[1px]">
          <p className="font-normal text-center text-md leading-[27px] text-gray-600 dark:text-gray-400">
            2023 Alerrandro Janio. All Rights Reserved.
          </p>
          <div className="flex flex-rox md:mt-0 m-4 gap-3 text-gray-600 dark:text-gray-400">
            <a
              href="https://www.linkedin.com/in/alerrandrojanio/"
              target="_blank"
              without
              rel="noreferrer"
            >
              <AiFillLinkedin
                size={"24px"}
                className=" hover:text-teal-500  dark:hover:text-teal-500"
              />
            </a>
            <a
              href="https://www.github.com/alerrandrojanio"
              target="_blank"
              without
              rel="noreferrer"
            >
              <AiOutlineGithub
                size={"24px"}
                className=" hover:text-teal-500  dark:hover:text-teal-500"
              />
            </a>
            <a
              href="https://www.instagram.com/alerrandrojanio"
              target="_blank"
              without
              rel="noreferrer"
            >
              <AiOutlineInstagram
                size={"24px"}
                className=" hover:text-teal-500  dark:hover:text-teal-500"
              />
            </a>
          </div>
        </div>
      </main>
    </div>
  )
}
